### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ysm1mh** [flakas/reconbot#2]
Traceback (most recent call last):
  File "run.py", line 198, in <module>
    schedule.run_pending()
  File "/usr/lib/python3.6/site-packages/schedule/__init__.py", line 367, in run_pending
    default_scheduler.run_pending()
  File "/usr/lib/python3.6/site-packages/schedule/__init__.py", line 64, in run_pending
    self._run_job(job)
  File "/usr/lib/python3.6/site-packages/schedule/__init__.py", line 96, in _run_job
    ret = job.run()
  File "/usr/lib/python3.6/site-packages/schedule/__init__.py", line 293, in run
    ret = self.job_func()
  File "run.py", line 179, in notifications_job_logistics
    eve_apis['example-group']['notifications'],
KeyError: 'example-group'

not sure what is going on. can someone explain?

**Comment by flakas** [comment]
Hey @ysm1mh ,

Thanks for the issue report.

The issue seems to be that the provided example `run.py` is not fully correct.
[This dict](https://github.com/flakas/reconbot/blob/3c55ae91e844cb23f904fb8ad059d34406e9ecb4/run.py#L179) was intended to reference [logistics configuration group](https://github.com/flakas/reconbot/blob/3c55ae91e844cb23f904fb8ad059d34406e9ecb4/run.py#L94).

You can pull again from `master` to see the fixed version in e24693f.
